---
- name: Install Apache on RedHat
  yum: name=httpd state=present

- name: Enable Apache
  service: name=httpd enabled=yes

- name: Restart Apache
  service: name=httpd state=restarted

- name: Compile and install mod_fastcgi on RHEL
  include: fastcgi.yml
  notify: restart apache
